server:
  port: 8084

spring:
  application:
    name: application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/application_db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
